### ISSUE TITLE
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by rnakamine** [binkhq/certbot-dns-azure#4]
Sorry my bad english skills.

When I tried to run certbot using dns-azure as authenticator, I got the following error.
```sh
$ certbot certonly \
--authenticator dns-azure \
--preferred-challenges dns \
--noninteractive \
--agree-tos \
--email rnakamine@example.com \
--dns-azure-config azure.ini \
--config-dir config-dir/ \
--work-dir work-dir/ \
--logs-dir logs-dir/ \
--cert-name example.com \
--domains example.com
Saving debug log to /path/to/logs-dir/letsencrypt.log
Plugins selected: Authenticator dns-azure, Installer None
Account registered.
Requesting a certificate for example.com
Performing the following challenges:
dns-01 challenge for example.com
Cleaning up challenges
Encountered exception during recovery: AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
An unexpected error occurred:
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
Please see the logfiles in /path/to/logs-dir for more details.
```

This is due to the recent version release of azure-mgmt-dns.

- [Release azure\-mgmt\-dns\_8\.0\.0 · Azure/azure\-sdk\-for\-python](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-mgmt-dns_8.0.0)
- [azure\-mgmt\-dns · PyPI](https://pypi.org/project/azure-mgmt-dns/)

Versions 3.0.0 and 8.0.0 are not compatible.

I think this plugin needs to support version 8.0.0 of azure-mgmt-dns or fix the version of azure-mgmt-dns to 3.0.0, can you give me your opinion?

Created a Pull Request for each.

- [Support azure\-mgmt\-dns 8\.0\.0 by rnakamine · Pull Request \#5 · binkhq/certbot\-dns\-azure](https://github.com/binkhq/certbot-dns-azure/pull/5)
- [Fixed major version by rnakamine · Pull Request \#6 · binkhq/certbot\-dns\-azure](https://github.com/binkhq/certbot-dns-azure/pull/6)

**Comment by terrycain** [comment]
Moving to v8 is the way to go, just merged one of the PRs, will get back to you when its released

**Comment by terrycain** [comment]
v1.1.0 is released

**Comment by rnakamine** [comment]
Thanks!
