### ISSUE TITLE
Wildcard cert issue with base domain

### ISSUE THREAD

**Issue by mrrsm** [binkhq/certbot-dns-azure#9]
I am attempting to register *.subdomain.example.com and subdomain.example.com in the same request.  I always get an error that it can't validate the TXT record on one of the two domains that are listed.  If I do them one at a time things seem to work just fine.

This seems like it may be the same issue that was talked about here https://github.com/certbot/certbot/issues/5673

`certbot certonly --authenticator dns-azure --preferred-challenges dns --noninteractive --agree-tos --email certbot@example.com --dns-azure-config /etc/azure.ini -d subdomain.example.com -d *.subdomain.example.com`

**Comment by terrycain** [comment]
Ahhhh, I have a feeling I know where this is breaking. I will look into it this week as it should be an easy fix.

**Comment by filipisaci** [comment]
I had the same problem for wildcards.

**Comment by moriyoshi** [comment]
@mrrsm I'm not a contributor of this project, but can you please test https://github.com/binkhq/certbot-dns-azure/pull/10 if you have time?  My fix worked for several configurations of mine and I just want to see how it will do for others.

**Comment by terrycain** [comment]
Can someone test out the beta `certbot-dns-azure==1.3.0b0` i've just released. Assuming its all good I'll release `1.3.0`

**Comment by mrrsm** [comment]
@terrycain I was able to successfully test running `certbot renew` with `certbot-dns-azure==1.3.0b0`
I should be able to test a fresh setup in a little while as well.

**Comment by mrrsm** [comment]
@terrycain The fix seems to be working for both renews as well as new certs.  Thanks for packaging the release, can't wait for the GA release

@moriyoshi Thanks for the fix!

**Comment by terrycain** [comment]
1.3.0 is out 😄  thanks all for helping with this!

**Comment by filipisaci** [comment]
1.3.0 It's works for me too!

Thank you very much!
